name: Geant4 Test
on: [push]
jobs:
  geant4-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check trigger 
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Install dependencies
        run: sudo apt-get install libxerces-c-dev
      - name: Install Geant4
        run: |
          wget https://github.com/hahnjo/geant4-actions-binaries/releases/download/$GEANT4_VERSION/$GEANT4_VERSION-binaries.tar.gz
          tar xf $GEANT4_VERSION-binaries.tar.gz -C $HOME
        env:
          GEANT4_VERSION: "geant4.10.07.p03"
      - uses: actions/checkout@v2
      - name: Build application
        run: |
          source ~/Geant4/bin/geant4.sh
          mkdir build
          cd build
          cmake -DGeant4_DIR=~/Geant4/lib/Geant4-10.7.3/ ../
      - name: Run application (single thread, FTFP_BERT)
          ./ATLHECTB -m ATLHECTB_run.mac -t 1
          ls -ltr

