name: Geant4 Test
on: [push]
jobs:
  geant4-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check trigger 
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
